language: php
php:
  - '7.1.33'
  - '7.2'
  - '7.3'
  - '7.4'
  - '8.0'
  - nightly
matrix:
  allow_failures:
    -   php: nightly
install:
  - composer install
script:
  - ./vendor/bin/phpunit --coverage-clover ./tests/Logs/clover.xml
  - ./vendor/bin/psalm
after_script:
  - php vendor/bin/php-coveralls -v
